spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://adniadni04_db_user:adniadni1234@user-data.zbv41r2.mongodb.net/?appName=user-data
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5433/userdb
#    username: postgres
#    password: postgres
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8082

